### ISSUE TITLE
Android - Firefox does not show day of week in English in list of events

### ISSUE THREAD

**Issue by OneHwang** [Shift2Bikes/shiftcal#114]
It  shows date in form mm/dd/yyyy, but should display day of week, month, date spelled out in English

**Comment by carrythebanner** [comment]
This is an old issue and appears to have been fixed in the interim. I tested with the latest Firefox on an Android 7.1.1 device and all dates displayed as I would expect.

**Comment by carrythebanner** [comment]
Closing this issue. If this resurfaces, please file another issue.
