### ISSUE TITLE
wheres the includes.tgz file?

### ISSUE THREAD

**Issue by digitalcake** [Shift2Bikes/shiftcal#135]

**Comment by OneHwang** [comment]
I believe @fool had the file unpacked here: https://github.com/Shift2Bikes/shiftcal/tree/Legacy/include

Can you try installing the Legacy branch first and then do a pull to get the code on the master branch?

**Comment by digitalcake** [comment]
thank you

**Comment by digitalcake** [comment]
So I assumed that the data base schema was possibly included with the inclues.tgz file but I'm not able to locate any file that resembles something that would run a migration on the db or a raw schema dump from mysql or postgres.  how would stand up the db for this app?

**Comment by OneHwang** [comment]
Sorry for the slow response. I think it'd be good to meet in person. What's your availability this weekend? Ping me at onekhwang at gmail. Thanks.

**Comment by digitalcake** [comment]
ok sure thing.

**Comment by fool** [comment]
so - to finally resolve this (sorry I didn't notice the thread earlier!) you no longer need includes.tgz.  Instructions updated to reflect this.
