### ISSUE TITLE
Can we set up coordination for events between bike calendars?

### ISSUE THREAD

**Issue by CorySpitzer** [Shift2Bikes/shiftcal#14]
Maybe using some of the JSON/api thing we worked on at the hackathon today.

**Comment by kirkendall** [comment]
Exporting events should be easy via either ical.php or the JSON derivative.

There's already a mechanism for importing events from the Wheelmen's calendar via their RSS feed. There are two fields in shiftcal's "calevent" table to manage this: source and external.  source is a unique id identifying the feed, and external is a unique id identifying the event from that source.  For the Wheelmen, source is "www.pwtc.com" and external is a link to the event, parsed from the RSS feed.  It works, but their RSS feed never did give us all the events, and the Wheelmen lost interest pretty quickly.  With their reputation for stodginess in insularity, I'm surprised they floated the idea at all.

Hey, Cory, please email me!  kirkenda@gmail.com
