### ISSUE TITLE
Slim down the top navigation items

### ISSUE THREAD

**Issue by tommctighe** [Shift2Bikes/shiftcal#17]
Let’s look at the top navigation items, would be great to limit them to 5-6 items. What are the best names for the nav items? The current 8-item, 102-character list breaks the nav for tablet users, because it’s too long. Will have to get buy-in from all the website admins, as this would affect all of the site's pages.

Here's a draft: 
    Calendar
    Special Events
    Discussion
    Safety
    Who We Are

**Comment by fool** [comment]
hmm, I think all of the current items are pretty important and we'd want Thom and Brian in on the discussion about changing the list substantively...any chance we could switch to a 2-line layout or a horizontal layout or similar? no complaints about shrinking things down though:



Who We Are  + Contact could probably be merged into one page.

 Calendar -> cal
BreakfastontheBridges -> BonB
 PedalPalooza |  List |  Safety | biki  ->  should maybe stay the same.

**Comment by fool** [comment]
heya @tommctighe do you think that my suggestion above will fit?

**Comment by tommctighe** [comment]
We'll want to keep the menu labels easy for new visitors to quickly
understand, so let's keep the longer names until we can talk to the other
webmasters.

In the meantime we can make the longer names work in the responsive version
by going to the hamburger menu for screens under 950px wide.

**Comment by OneHwang** [comment]
We will limit the navigation bar to Events, Add Events, Pedalpalooza, Old website, and About.
