### ISSUE TITLE
Event images don't load on betacal

### ISSUE THREAD

**Issue by carrythebanner** [Shift2Bikes/shiftcal#177]
Steps:
1. Load events beta calendar page: http://www.shift2bikes.org/betacal/
2. View any ride with an event image

Result:
The event image is broken. 

Images *do* load as expected on http://www.shift2bikes.org/fun/ and http://www.shift2bikes.org/fun2/.

**Comment by carrythebanner** [comment]
@sdobz This was recently fixed on /fun, with a config change I think. Can we apply that same change on /betacal?

**Comment by OneHwang** [comment]
Images work fine now. Example: [The Welcome Ride](http://www.shift2bikes.org/betacal/event-11033)
