### ISSUE TITLE
Betacal is missing "delete" and "cancel" event buttons

### ISSUE THREAD

**Issue by OneHwang** [Shift2Bikes/shiftcal#190]
I click on the link for managing an event that I created, which begins with in shift2bikes.org/betacal. I do not see a "delete" or "cancel" button.

**Comment by carrythebanner** [comment]
@OneHwang Can you share the edit link with me privately so I can troubleshoot?

**Comment by carrythebanner** [comment]
FWIW, when you edit an event, there is not currently a Cancel button (as in, "cancel this ride"). The "Add Event" form does have a Cancel button, but as in "forget it, don't create this event." 

Also, the Delete button was recently moved to the end of the Edit Event form.

**Comment by carrythebanner** [comment]
Closing this issue. If there's something I overlooked in my previous comment, please reopen or file a new issue.
