### ISSUE TITLE
Can we streamline local setup for new users with Gulp?

### ISSUE THREAD

**Issue by georgemandis** [Shift2Bikes/shiftcal#40]
I see at least a few places incorporating a build system like [Gulp](http://gulpjs.com) could be beneficial to this project:

- We could streamline local setup with tasks that do a lot of the heavy-lifting (Extracting the tar and the SQL dump could be relegated to a single `gulp setup` command run from the project root, for example). 
- We could concatenate and minify the CSS/JavaScript that gets output for production and adopt a preprocessor like SASS, eventually.
-  We could even create simple tests that lets you know if your code additions break any existing/important features elsewhere on the site.

Gulp has a lot of traction these days and I'm rather fond of it for my own work and projects. Curious to hear other people's thoughts!

**Comment by CorySpitzer** [comment]
I don't have XP with Gulp but that all sounds good!

**Comment by fool** [comment]
I've seen gulp used successfully and it seems like a great idea.

**Comment by OneHwang** [comment]
It's unclear why gulp would be better than the jQuery/flourish combo we're using now.
