### ISSUE TITLE
Make it mobile friendly

### ISSUE THREAD

**Issue by CorySpitzer** [Shift2Bikes/shiftcal#6]
Lets make the site look good for mobile and small screens. Maybe with [Bootstrap](http://getbootstrap.com).

**Comment by tommctighe** [comment]
I'm working on this, using Bootstrap - will hopefully have something in a couple days.

**Comment by fool** [comment]
I think that the test site looks pretty good in mobile screens (the 'hamburger' menu seems to work) when using the bootstrap version:  http://shift2bikes.org/testcal/view2week-bs.php

**Comment by OneHwang** [comment]
We are now using a different code base that is mobile friendly.
