### ISSUE TITLE
betacal cannot be auto-pulled from git right now

### ISSUE THREAD

**Issue by fool** [Shift2Bikes/shiftcal#99]
at present, this line of code has been patched live on the server:

https://github.com/Shift2Bikes/shiftcal/blob/master/www/main.js#L154

to refer to /pedalpalooza instead of /cal to support Thom's redirect wizardry.

As such no more automatic pulling works.  I guess this won't be a problem in a week since we'll want to redirect elsewhere and can resolve it then, but wanted to let the team know what is happening with auto-pulls right now (i re-patched it after one's scroll-to-top pull request was merged so we are current)

**Comment by OneHwang** [comment]
Right now, shift2bikes.org/betacal automatically goes to http://shift2bikes.org/betacal/www/#pedalpalooza
When Pedalpalooza is over, we want it to go to http://www.shift2bikes.org/betacal/www/#viewEvents

**Comment by fool** [comment]
I fixed the merge conflict so that your change could be auto-pulled and all's well, so closing this issue
